on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 10
      uses: actions/setup-node@v2-beta
      with:
        node-version: '10'
      
    - name: 🔨 Build Project
      env:
        CI: false
      run: |
        # cd app
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.merbeth.dev
        username: superuser@merbeth.dev
        password: ${{ secrets.ncpw }}
        local-dir: ./build/
        server-dir: ./public_html/projects/nft-ne-fu1/
